#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2018/3/13 17:05
# @Author  : Weiqiang.long
# @Site    : 
# @File    : test_suite.py
# @Software: PyCharm

import unittest
from test.case.test_mathfunc import TestMathFunc
from utils.HTMLTestRunner import HTMLTestRunner
from utils.config import Config, LOG_PATH

# if __name__ == '__main__':
#     suite = unittest.TestSuite()
#
#     tests = [TestMathFunc("test_add"), TestMathFunc("test_minus"), TestMathFunc("test_divide")]
#     suite.addTests(tests)
#
#     runner = unittest.TextTestRunner(verbosity=2)
#     runner.run(suite)

if __name__ == '__main__':
    suite = unittest.TestSuite()
    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(TestMathFunc))

    # with open('UnittestTextReport.txt', 'a') as f:
    #     runner = unittest.TextTestRunner(stream=f, verbosity=2)
    #     runner.run(suite)

    # 用HTMLTestRunner输入报告
    with open('HTMLReport.html', 'wb') as f:
        runner = HTMLTestRunner(stream=f,
                                title='MathFunc Test Report',
                                description='generated by HTMLTestRunner.',
                                verbosity=2
                                )
        runner.run(suite)